import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider, SignInButton, SignUpButton, Show, UserButton } from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import { buttonVariants } from "@/components/ui/button-variants";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { Dumbbell } from "lucide-react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
<ThemeProvider defaultTheme="system">
          <ClerkProvider>
            <header className="flex items-center justify-between gap-4 px-6 py-3 border-b">
              <Link
                href="/dashboard"
                className="text-xl font-semibold tracking-tight hover:opacity-75 transition-opacity"
              >
                Lifting Dairy
              </Link>

              <div className="flex items-center gap-3">
                <Show when="signed-in">
                  <Link
                    href="/dashboard"
                    className={buttonVariants({ variant: "ghost", size: "sm" })}
                  >
                    <Dumbbell className="size-4" />
                    Dashboard
                  </Link>
                </Show>
                <ThemeToggle />
                <Show when="signed-out">
                  <>
                    <SignInButton mode="modal">
                      <button className={buttonVariants({ variant: "outline", size: "sm" })}>Sign In</button>
                    </SignInButton>
                    <SignUpButton mode="modal">
                      <button className={buttonVariants({ size: "sm" })}>Sign Up</button>
                    </SignUpButton>
                  </>
                </Show>
                <Show when="signed-in">
                  <UserButton />
                </Show>
              </div>
            </header>
            {children}
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
